const fetchedForecast = [{
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 94,
    'temperature': {
        'curr': 267,
        'min': 265,
        'max': 267,
    },
    'pressure': 1008.75,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 56,
    'wind': {
        'speed': 3.57,
    },
    'rain': null,
    'snow': 0.0325,
    'calculationTime': 1485864000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 86,
    'temperature': {
        'curr': 265,
        'min': 264,
        'max': 265,
    },
    'pressure': 1008.89,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 64,
    'wind': {
        'speed': 2.87,
    },
    'rain': null,
    'snow': 0.0275,
    'calculationTime': 1485874800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 88,
    'temperature': {
        'curr': 265,
        'min': 264,
        'max': 265,
    },
    'pressure': 1009.16,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 68,
    'wind': {
        'speed': 3.11,
    },
    'rain': null,
    'snow': 0.0425,
    'calculationTime': 1485885600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 86,
    'temperature': {
        'curr': 264,
        'min': 263,
        'max': 264,
    },
    'pressure': 1008.85,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.62,
    },
    'rain': null,
    'snow': 0.0225,
    'calculationTime': 1485896400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 81,
    'temperature': {
        'curr': 263,
        'min': 263,
        'max': 263,
    },
    'pressure': 1008.81,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.36,
    },
    'rain': null,
    'snow': 0.0125,
    'calculationTime': 1485907200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 83,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1009.04,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.36,
    },
    'rain': null,
    'snow': 0.0425,
    'calculationTime': 1485918000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 86,
    'temperature': {
        'curr': 263,
        'min': 263,
        'max': 263,
    },
    'pressure': 1009.53,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.6,
    },
    'rain': null,
    'snow': 0.07,
    'calculationTime': 1485928800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 91,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1009.96,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 44,
    'wind': {
        'speed': 1.98,
    },
    'rain': null,
    'snow': 0.055,
    'calculationTime': 1485939600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 94,
    'temperature': {
        'curr': 266,
        'min': 266,
        'max': 266,
    },
    'pressure': 1009.84,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 48,
    'wind': {
        'speed': 2.01,
    },
    'rain': null,
    'snow': 0.03,
    'calculationTime': 1485950400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 89,
    'temperature': {
        'curr': 265,
        'min': 265,
        'max': 265,
    },
    'pressure': 1009.97,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.61,
    },
    'rain': null,
    'snow': 0.025,
    'calculationTime': 1485961200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 85,
    'temperature': {
        'curr': 265,
        'min': 265,
        'max': 265,
    },
    'pressure': 1009.95,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 76,
    'wind': {
        'speed': 1.45,
    },
    'rain': null,
    'snow': 0.0475,
    'calculationTime': 1485972000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 88,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1009.83,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.66,
    },
    'rain': null,
    'snow': 0.055,
    'calculationTime': 1485982800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 93,
    'temperature': {
        'curr': 263,
        'min': 263,
        'max': 263,
    },
    'pressure': 1010.22,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 68,
    'wind': {
        'speed': 1.6,
    },
    'rain': null,
    'snow': 0.0525,
    'calculationTime': 1485993600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 91,
    'temperature': {
        'curr': 263,
        'min': 263,
        'max': 263,
    },
    'pressure': 1010.15,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 68,
    'wind': {
        'speed': 1.2,
    },
    'rain': null,
    'snow': 0.065,
    'calculationTime': 1486004400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 87,
    'temperature': {
        'curr': 262,
        'min': 262,
        'max': 262,
    },
    'pressure': 1010.17,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 64,
    'wind': {
        'speed': 1.71,
    },
    'rain': null,
    'snow': 0.0625,
    'calculationTime': 1486015200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 93,
    'temperature': {
        'curr': 263,
        'min': 263,
        'max': 263,
    },
    'pressure': 1010.4,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 56,
    'wind': {
        'speed': 2.56,
    },
    'rain': null,
    'snow': 0.045,
    'calculationTime': 1486026000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 90,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1009.87,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 76,
    'wind': {
        'speed': 3.02,
    },
    'rain': null,
    'snow': 0.0425,
    'calculationTime': 1486036800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 86,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1009.61,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 88,
    'wind': {
        'speed': 3.23,
    },
    'rain': null,
    'snow': 0.0775,
    'calculationTime': 1486047600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 87,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1009.36,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 88,
    'wind': {
        'speed': 3.78,
    },
    'rain': null,
    'snow': 0.135,
    'calculationTime': 1486058400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 88,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1008.5,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 92,
    'wind': {
        'speed': 3.92,
    },
    'rain': null,
    'snow': 0.12,
    'calculationTime': 1486069200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 92,
    'temperature': {
        'curr': 265,
        'min': 265,
        'max': 265,
    },
    'pressure': 1007.7,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 76,
    'wind': {
        'speed': 4.08,
    },
    'rain': null,
    'snow': 0.07,
    'calculationTime': 1486080000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 90,
    'temperature': {
        'curr': 266,
        'min': 266,
        'max': 266,
    },
    'pressure': 1006.78,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 68,
    'wind': {
        'speed': 4.01,
    },
    'rain': null,
    'snow': 0.075,
    'calculationTime': 1486090800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 93,
    'temperature': {
        'curr': 266,
        'min': 266,
        'max': 266,
    },
    'pressure': 1006.29,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 68,
    'wind': {
        'speed': 3.91,
    },
    'rain': null,
    'snow': 0.05,
    'calculationTime': 1486101600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 95,
    'temperature': {
        'curr': 267,
        'min': 267,
        'max': 267,
    },
    'pressure': 1006.12,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 64,
    'wind': {
        'speed': 4.11,
    },
    'rain': null,
    'snow': 0.025,
    'calculationTime': 1486112400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 92,
    'temperature': {
        'curr': 269,
        'min': 269,
        'max': 269,
    },
    'pressure': 1005.31,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 12,
    'wind': {
        'speed': 3.78,
    },
    'rain': null,
    'snow': 0.005,
    'calculationTime': 1486123200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 87,
    'temperature': {
        'curr': 266,
        'min': 266,
        'max': 266,
    },
    'pressure': 1005.61,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 8,
    'wind': {
        'speed': 3.41,
    },
    'rain': null,
    'calculationTime': 1486134000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 79,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1006,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'few clouds',
    }],
    'clouds': 24,
    'wind': {
        'speed': 4.01,
    },
    'rain': null,
    'calculationTime': 1486144800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 86,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1006.09,
    'weatherTypes': [{
        'main': 'cloudy',
        'desc': 'clear sky',
    }],
    'clouds': 64,
    'wind': {
        'speed': 4.22,
    },
    'rain': null,
    'snow': 0.01,
    'calculationTime': 1486155600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 87,
    'temperature': {
        'curr': 263,
        'min': 263,
        'max': 263,
    },
    'pressure': 1006.38,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 56,
    'wind': {
        'speed': 3.86,
    },
    'rain': null,
    'snow': 0.055,
    'calculationTime': 1486166400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 88,
    'temperature': {
        'curr': 262,
        'min': 262,
        'max': 262,
    },
    'pressure': 1006.56,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 64,
    'wind': {
        'speed': 3.67,
    },
    'rain': null,
    'snow': 0.05,
    'calculationTime': 1486177200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 84,
    'temperature': {
        'curr': 262,
        'min': 262,
        'max': 262,
    },
    'pressure': 1007.04,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 76,
    'wind': {
        'speed': 3.88,
    },
    'rain': null,
    'snow': 0.045,
    'calculationTime': 1486188000000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 93,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1007.62,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 68,
    'wind': {
        'speed': 4.02,
    },
    'rain': null,
    'snow': 0.055,
    'calculationTime': 1486198800000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 92,
    'temperature': {
        'curr': 265,
        'min': 265,
        'max': 265,
    },
    'pressure': 1007.36,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 76,
    'wind': {
        'speed': 3.37,
    },
    'rain': null,
    'snow': 0.04,
    'calculationTime': 1486209600000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 87,
    'temperature': {
        'curr': 265,
        'min': 265,
        'max': 265,
    },
    'pressure': 1007.47,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 80,
    'wind': {
        'speed': 2.97,
    },
    'rain': null,
    'snow': 0.05,
    'calculationTime': 1486220400000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 87,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1007.43,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 80,
    'wind': {
        'speed': 3.11,
    },
    'rain': null,
    'snow': 0.06,
    'calculationTime': 1486231200000,
}, {
    'metric': 'c',
    'status': 200,
    'city': 'Minsk',
    'humidity': 86,
    'temperature': {
        'curr': 264,
        'min': 264,
        'max': 264,
    },
    'pressure': 1007.35,
    'weatherTypes': [{
        'main': 'snowy',
        'desc': 'light snow',
    }],
    'clouds': 80,
    'wind': {
        'speed': 2.57,
    },
    'rain': null,
    'snow': 0.075,
    'calculationTime': 1486242000000,
}];

export default fetchedForecast;
