export const SET_CITY = 'SET_CITY';
export const UPDATE_WEATHER_INFO = 'UPDATE_WEATHER_INFO';
export const UPDATE_FORECAST = 'UPDATE_FORECAST';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const SET_AUTOCOMPLETE_ARRAY = 'SET_AUTOCOMPLETE_ARRAY';
export const SET_NEAREST_CITIES = 'SET_NEAREST_CITIES';
